name: CI/CD

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish with dotnet
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: artifacts/

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-githubactionsapi-dev
          package: artifacts/

  deploy-prod:
      name: Deploy Prod
      runs-on: ubuntu-latest
      needs: deploy-dev
      environment: prod

      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: publish-artifact
            path: artifacts/

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: 'Deploy to Azure App Service'
          uses: azure/webapps-deploy@v2
          with: 
            app-name: app-githubactionsapi-prod
            package: artifacts/
