# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
name: Run 1st of the Month at 5 past midnight

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 1 * *'

jobs:
  build:
    name: Run CRON 
    runs-on: ubuntu-latest

    steps:
      - name: ECHO
        run: echo 'The cron job ran'
