name: Secrets workflow

on:
  pull_request:
     branches:
     - main

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj" # non secret secrets. No api keys and such here

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: Echo environment variable
        run: echo "$API_CSPROJ_PATH"
