name: Secrets workflow

on:
  pull_request:
     branches:
     - main

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj" # non secret secrets. No api keys and such here

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: Echo root environment variable
        run: echo "$API_CSPROJ_PATH"

    steps:
      - name: Echo job environment variable
        run: echo "The value of JOB_NAME is $JOB_NAME" 
